services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dyelog:${DYELOG_VERSION:-latest}
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/.config/gcloud/application_default_credentials.json:/creds.json
    labels:
      # Enables traefik for this container.
      - traefik.enable=true
      - traefik.http.routers.dyelog.rule=Host(`${DYELOG_TRAEFIK_HOST:-dyelog.localhost}`)
      - traefik.http.routers.dyelog.entrypoints=http
      - traefik.http.routers.dyelog.service=dyelog
      - traefik.http.services.dyelog.loadbalancer.server.port=${DYELOG_PORT:-8000}
    networks:
      - default
      - traefik-shared
    environment:
      DYELOG_HOST: 0.0.0.0

      GOOGLE_APPLICATION_CREDENTIALS: /creds.json
    network_mode: host

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
